spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greensportal
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update